-- MySQL Script generated by MySQL Workbench
-- 10/10/14 18:20:52
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema intosport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `intosport` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `intosport` ;

-- -----------------------------------------------------
-- Table `intosport`.`persoon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intosport`.`persoon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `voornaam` VARCHAR(45) NULL,
  `tv` VARCHAR(5) NULL,
  `achternaam` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intosport`.`personeel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intosport`.`personeel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persoon_id` INT NULL,
  `role` ENUM('0', '1', '2') NULL DEFAULT '0' COMMENT '0 = beheerder, 1 = manager, 2 = allebei',
  PRIMARY KEY (`id`),
  INDEX `persoon_id_idx` (`persoon_id` ASC),
  CONSTRAINT `persoon_id`
    FOREIGN KEY (`persoon_id`)
    REFERENCES `intosport`.`persoon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intosport`.`klant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intosport`.`klant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persoon2_id` INT NULL,
  `adres` VARCHAR(45) NULL,
  `postcode` VARCHAR(6) NULL,
  `plaats` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `goldmember` ENUM('0', '1') NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `persoon_id2_idx` (`persoon2_id` ASC),
  CONSTRAINT `persoon2_id`
    FOREIGN KEY (`persoon2_id`)
    REFERENCES `intosport`.`persoon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intosport`.`orderregel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intosport`.`orderregel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hoeveelheid` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intosport`.`bestelling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intosport`.`bestelling` (
  `klant_id` INT NOT NULL,
  `orderregel_id` INT NOT NULL,
  `status` ENUM('0', '1', '2', '3') NULL DEFAULT '0',
  PRIMARY KEY (`klant_id`, `orderregel_id`),
  INDEX `orderregel_id_idx` (`orderregel_id` ASC),
  CONSTRAINT `orderregel_id`
    FOREIGN KEY (`orderregel_id`)
    REFERENCES `intosport`.`orderregel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `klant_id`
    FOREIGN KEY (`klant_id`)
    REFERENCES `intosport`.`klant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intosport`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intosport`.`categorie` (
  `id` INT NOT NULL,
  `subcategorie_id` INT NULL,
  `naam` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intosport`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intosport`.`product` (
  `id` INT NOT NULL,
  `orderregel2_id` INT NULL,
  `categorie_id` INT NULL,
  `naam` VARCHAR(45) NULL,
  `prijs` DOUBLE NULL,
  `prijs_oud` DOUBLE NULL,
  `hoeveelheid` INT NULL,
  `merk` VARCHAR(45) NULL,
  `maat` VARCHAR(45) NULL,
  `afbeelding` VARCHAR(45) NULL,
  `thumbnail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `orderregel2_id_idx` (`orderregel2_id` ASC),
  INDEX `categorie_id_idx` (`categorie_id` ASC),
  CONSTRAINT `orderregel2_id`
    FOREIGN KEY (`orderregel2_id`)
    REFERENCES `intosport`.`orderregel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categorie_id`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `intosport`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

