-- MySQL Script generated by MySQL Workbench
-- 10/12/14 19:22:36
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema intosport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `intosport` DEFAULT CHARACTER SET utf8 ;
USE `intosport` ;

-- -----------------------------------------------------
-- Table `intosport`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intosport`.`categorie` (
  `naam` VARCHAR(45) NOT NULL,
  `sub` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`naam`),
  INDEX `sub_idx` (`sub` ASC),
  CONSTRAINT `sub`
    FOREIGN KEY (`sub`)
    REFERENCES `intosport`.`categorie` (`naam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `intosport`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intosport`.`order` (
  `klant_id` INT(11) NOT NULL,
  `regel_id` INT(11) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`klant_id`, `regel_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `intosport`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intosport`.`product` (
  `id` INT(11) NOT NULL,
  `prijs` INT(11) NULL DEFAULT NULL,
  `prijs_oud` INT(11) NULL DEFAULT NULL,
  `hoeveelheid` INT(11) NULL DEFAULT NULL,
  `afbeelding` VARCHAR(200) NULL DEFAULT NULL,
  `thumbnail` VARCHAR(200) NULL DEFAULT NULL,
  `merk` VARCHAR(45) NULL DEFAULT NULL,
  `maat` VARCHAR(45) NULL DEFAULT NULL,
  `catergorie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categorie_idx` (`catergorie` ASC),
  CONSTRAINT `categorie`
    FOREIGN KEY (`catergorie`)
    REFERENCES `intosport`.`categorie` (`naam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `intosport`.`orderregel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intosport`.`orderregel` (
  `product_id` INT(11) NOT NULL,
  `hoeveelheid` INT(11) NOT NULL,
  `maat` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `intosport`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `intosport`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intosport`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `voornaam` VARCHAR(45) NOT NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `straat` VARCHAR(45) NOT NULL,
  `huisnr` VARCHAR(15) NOT NULL,
  `postcode` VARCHAR(6) NOT NULL,
  `plaats` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `wachtwoord` VARCHAR(45) NOT NULL,
  `role` ENUM('klant','beheerder','manager','alles') NOT NULL DEFAULT 'klant',
  `goldmember` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
